In [1]:
!pip uninstall numpy -y

Found existing installation: numpy 1.26.4
Uninstalling numpy-1.26.4:
  Successfully uninstalled numpy-1.26.4


In [2]:
!pip install numpy==1.26.4

  Using cached numpy-1.26.4-cp310-cp310-win_amd64.whl.metadata (61 kB)
Using cached numpy-1.26.4-cp310-cp310-win_amd64.whl (15.8 MB)


ERROR: pip's dependency resolver does not currently take into account all the packages that are installed. This behaviour is the source of the following dependency conflicts.
mediapipe 0.10.14 requires protobuf<5,>=4.25.3, but you have protobuf 3.19.4 which is incompatible.


In [3]:
!pip install -U scikit-learn

  Using cached joblib-1.4.2-py3-none-any.whl.metadata (5.4 kB)
  Using cached threadpoolctl-3.5.0-py3-none-any.whl.metadata (13 kB)
   ---------------------------------------- 0.0/11.0 MB ? eta -:--:--
   ---------------------------------------- 0.0/11.0 MB 1.9 MB/s eta 0:00:06
   - -------------------------------------- 0.5/11.0 MB 5.9 MB/s eta 0:00:02
   ---- ----------------------------------- 1.1/11.0 MB 8.8 MB/s eta 0:00:02
   ------- -------------------------------- 2.1/11.0 MB 11.9 MB/s eta 0:00:01
   ----------- ---------------------------- 3.2/11.0 MB 15.9 MB/s eta 0:00:01
   ------------ --------------------------- 3.5/11.0 MB 14.9 MB/s eta 0:00:01
   ------------- -------------------------- 3.8/11.0 MB 13.6 MB/s eta 0:00:01
   -------------------- ------------------- 5.6/11.0 MB 17.1 MB/s eta 0:00:01
   --------------------------- ------------ 7.6/11.0 MB 20.2 MB/s eta 0:00:01
   ------------------------------- -------- 8.8/11.0 MB 21.5 MB/s eta 0:00:01
   ------------------

In [4]:
import numpy as np
import glob
import os
from tensorflow.keras.utils import to_categorical
from sklearn.model_selection import train_test_split
from tensorflow.keras.models import Sequential
from tensorflow.keras.layers import LSTM, Dense, Flatten, Dropout
from tensorflow.keras.callbacks import ModelCheckpoint, EarlyStopping

In [5]:
#GPU 사용하도록 설정
os.environ["CUDA_VISIBLE_DEVICES"] = "0"

In [6]:
#예측값과 문자열

gesture = {
    0:'A', 1:'B', 2:'C', 3:'D', 4:'E', 5:'F',
    6:'G', 7:'H', 8:'I', 9:'J'
}

In [7]:
#예측값과 문자열의 종류
len(gesture)

10

In [8]:
#학습 데이터의 경로
path = "C://ai_project01/hand_detect01/hand_dataset/*.npy"

In [10]:
#glob.glob(path) : path 경로의 파일 리스트 리턴
file_list = glob.glob(path)

file_list

['C://ai_project01/hand_detect01/hand_dataset\\A_1721722804.npy',
 'C://ai_project01/hand_detect01/hand_dataset\\B_1721780703.npy',
 'C://ai_project01/hand_detect01/hand_dataset\\C_1721780752.npy',
 'C://ai_project01/hand_detect01/hand_dataset\\D_1721780799.npy',
 'C://ai_project01/hand_detect01/hand_dataset\\E_1721780857.npy',
 'C://ai_project01/hand_detect01/hand_dataset\\F_1721780903.npy',
 'C://ai_project01/hand_detect01/hand_dataset\\G_1721780972.npy',
 'C://ai_project01/hand_detect01/hand_dataset\\H_1721781028.npy',
 'C://ai_project01/hand_detect01/hand_dataset\\I_1721781093.npy',
 'C://ai_project01/hand_detect01/hand_dataset\\J_1721781163.npy']

In [11]:
#file_list 디렉토리에 저장된 파일의 경로 1개를 file에 저장
for file in file_list:
    print("file=",file)
    #np.load(file) : file의 내용 리턴
    data = np.load(file)
    #data.shape : file의 내용이 저장된 데이터의 행 열의 개수
    print("data.shape=",data.shape)

file= C://ai_project01/hand_detect01/hand_dataset\A_1721722804.npy
data.shape= (640, 79)
file= C://ai_project01/hand_detect01/hand_dataset\B_1721780703.npy
data.shape= (583, 79)
file= C://ai_project01/hand_detect01/hand_dataset\C_1721780752.npy
data.shape= (592, 79)
file= C://ai_project01/hand_detect01/hand_dataset\D_1721780799.npy
data.shape= (573, 79)
file= C://ai_project01/hand_detect01/hand_dataset\E_1721780857.npy
data.shape= (568, 79)
file= C://ai_project01/hand_detect01/hand_dataset\F_1721780903.npy
data.shape= (580, 79)
file= C://ai_project01/hand_detect01/hand_dataset\G_1721780972.npy
data.shape= (572, 79)
file= C://ai_project01/hand_detect01/hand_dataset\H_1721781028.npy
data.shape= (569, 79)
file= C://ai_project01/hand_detect01/hand_dataset\I_1721781093.npy
data.shape= (576, 79)
file= C://ai_project01/hand_detect01/hand_dataset\J_1721781163.npy
data.shape= (583, 79)


In [13]:
#path 경로의 파일들의 내용을 저장할 리스트
data_list = []

#file_list 디렉토리에 저장된 파일의 경로 1개를 file에 저장
for file in file_list:
    print("file=",file)
    #np.load(file) : file의 내용 리턴
    data = np.load(file)
    print("data.shape=",data[ :560 :].shape)
    #파일의 내용이 저장된 data를 data list에 추가
    data_list.extend(data[ :560, :])

file= C://ai_project01/hand_detect01/hand_dataset\A_1721722804.npy
data.shape= (560, 79)
file= C://ai_project01/hand_detect01/hand_dataset\B_1721780703.npy
data.shape= (560, 79)
file= C://ai_project01/hand_detect01/hand_dataset\C_1721780752.npy
data.shape= (560, 79)
file= C://ai_project01/hand_detect01/hand_dataset\D_1721780799.npy
data.shape= (560, 79)
file= C://ai_project01/hand_detect01/hand_dataset\E_1721780857.npy
data.shape= (560, 79)
file= C://ai_project01/hand_detect01/hand_dataset\F_1721780903.npy
data.shape= (560, 79)
file= C://ai_project01/hand_detect01/hand_dataset\G_1721780972.npy
data.shape= (560, 79)
file= C://ai_project01/hand_detect01/hand_dataset\H_1721781028.npy
data.shape= (560, 79)
file= C://ai_project01/hand_detect01/hand_dataset\I_1721781093.npy
data.shape= (560, 79)
file= C://ai_project01/hand_detect01/hand_dataset\J_1721781163.npy
data.shape= (560, 79)


In [14]:
len(data_list)

5600

In [16]:
#np.array(data_list) : data_list를 배열로 변환
#dtype=np.float32 : 배열의 타입은 32비트 실수 float32로 변환

all_data = np.array(data_list, dtype=np.float32)

all_data

array([[ 1.3650388e-01,  5.8879721e-01, -2.3838011e-08, ...,
         1.8892279e+01,  1.0380528e+01,  0.0000000e+00],
       [ 1.3822445e-01,  6.1091161e-01,  8.9641032e-09, ...,
         2.7894497e+01,  8.4292974e+00,  0.0000000e+00],
       [ 1.3856648e-01,  5.9714860e-01, -2.9684021e-08, ...,
         2.2293457e+01,  1.0746673e+01,  0.0000000e+00],
       ...,
       [ 1.9912028e-01,  5.9498197e-01, -3.2183175e-07, ...,
         4.6131935e+00,  1.1724647e+00,  9.0000000e+00],
       [ 2.1990374e-01,  6.4319927e-01, -4.5523666e-07, ...,
         7.5301704e+00,  5.3254378e-01,  9.0000000e+00],
       [ 2.2928722e-01,  6.5826750e-01, -4.6250847e-07, ...,
         6.7613730e+00,  6.7632496e-01,  9.0000000e+00]], dtype=float32)

In [17]:
#전체 데이터의 행 열
all_data.shape

(5600, 79)

In [19]:
#all_data.reshape(-1,5,79) : all_data 배열의 차원을 (5600,79) -> (1120,5,79)으로 변환
#                            학습 시 5개 행씩 학습할 것임

#all_data.reshape(1120 => 5행 79열 2차원 배열의 개수 예에서는 1120,5 ==> 행의 개수, 79 ==> 열의 개수)

#all_data.reshape(-1 => 5행 79열 2차원 배열의 개수 예에서는 1120이나 -1로 생략 가능, 5 ==> 행의 개수, 79 ==> 열의 개수

all_data_lstm = all_data.reshape(-1,5,79)

#all_data_lstm의 행 열 조회
all_data_lstm.shape

(1120, 5, 79)

In [20]:
all_data_lstm

array([[[ 1.36503875e-01,  5.88797212e-01, -2.38380107e-08, ...,
          1.88922787e+01,  1.03805285e+01,  0.00000000e+00],
        [ 1.38224453e-01,  6.10911608e-01,  8.96410324e-09, ...,
          2.78944969e+01,  8.42929745e+00,  0.00000000e+00],
        [ 1.38566479e-01,  5.97148597e-01, -2.96840206e-08, ...,
          2.22934570e+01,  1.07466726e+01,  0.00000000e+00],
        [ 1.36480659e-01,  6.18827939e-01, -2.35372113e-08, ...,
          7.44722061e+01,  1.38268080e+01,  0.00000000e+00],
        [ 1.35352731e-01,  6.20294511e-01,  1.12828520e-08, ...,
          7.33151398e+01,  3.20096626e+01,  0.00000000e+00]],

       [[ 1.35141149e-01,  6.17969573e-01,  2.34940494e-08, ...,
          5.98485870e+01,  3.45335426e+01,  0.00000000e+00],
        [ 1.35970533e-01,  6.14740074e-01,  3.74642148e-08, ...,
          5.64226646e+01,  5.10361595e+01,  0.00000000e+00],
        [ 1.40326187e-01,  5.90316951e-01, -3.40871651e-08, ...,
          1.78916531e+01,  8.26650238e+00,  0.00000

In [22]:
#all_data_lstm[: => 모든 2차원 배열, : => 모든 행, :-1 => 마지막 열 제외]
#all_data_lstm의 마지막 열을 제외한 데이터 리턴 (손의 좌푣와 각도)

X_data = all_data_lstm [:, :, :-1]

X_data

array([[[ 1.36503875e-01,  5.88797212e-01, -2.38380107e-08, ...,
          2.00543156e+01,  1.88922787e+01,  1.03805285e+01],
        [ 1.38224453e-01,  6.10911608e-01,  8.96410324e-09, ...,
          6.02583694e+01,  2.78944969e+01,  8.42929745e+00],
        [ 1.38566479e-01,  5.97148597e-01, -2.96840206e-08, ...,
          3.38922615e+01,  2.22934570e+01,  1.07466726e+01],
        [ 1.36480659e-01,  6.18827939e-01, -2.35372113e-08, ...,
          6.00469589e+00,  7.44722061e+01,  1.38268080e+01],
        [ 1.35352731e-01,  6.20294511e-01,  1.12828520e-08, ...,
          2.53834858e+01,  7.33151398e+01,  3.20096626e+01]],

       [[ 1.35141149e-01,  6.17969573e-01,  2.34940494e-08, ...,
          2.96584530e+01,  5.98485870e+01,  3.45335426e+01],
        [ 1.35970533e-01,  6.14740074e-01,  3.74642148e-08, ...,
          3.47269783e+01,  5.64226646e+01,  5.10361595e+01],
        [ 1.40326187e-01,  5.90316951e-01, -3.40871651e-08, ...,
          1.81409931e+01,  1.78916531e+01,  8.26650

In [23]:
#all_data_lstm[: ,0, -1] : all_data_lstm의 첫번째 행 마지막 열데이터 리턴
#                         손의 좌표와 각도가 어떤 손모양인지 저장
#                         A일때는 0 B일때는 1 C일때는 2.. J:9가 저장되어있음
labels = all_data_lstm [: , 0, -1]

labels

array([0., 0., 0., ..., 9., 9., 9.], dtype=float32)

In [24]:
#to_categorical(labels, num_classes=len(gesture)) : 학습을 위해서 Labels 데이터를 수정
# labels 이 저장된 데이터가 0 (A) 일때는 -> 1000000000
# labels 이 저장된 데이터가 1 (B) 일때는 -> 0100000000
# labels 이 저장된 데이타가 2 (C) 일때는 -> 0010000000
# ...
#labels에 저장된 데이터가 9 (J) 일때는 -> 0000000001

# 10 자리 len(gesture) 로 변환

y_data = to_categorical(labels, num_classes=len(gesture))

y_data

array([[1., 0., 0., ..., 0., 0., 0.],
       [1., 0., 0., ..., 0., 0., 0.],
       [1., 0., 0., ..., 0., 0., 0.],
       ...,
       [0., 0., 0., ..., 0., 0., 1.],
       [0., 0., 0., ..., 0., 0., 1.],
       [0., 0., 0., ..., 0., 0., 1.]], dtype=float32)

In [25]:
#train_test_split(X_data, y_data, test_size=0.1) : X_data와 y_data를 학습데이터와 테스트 데이터로 분리
#테스트데이터는 전체 데이터의 10% 학습데이터는 전체 데이터의 90%로 설정

#학습 데이터는 LSTM에서 손모양의 패턴을 파악할 데이터
#즉 A손 모양의 좌표와 각도의 패턴 파악 데이터 B손 모양의 좌표와 각도의 패턴 파악 데이터 ... J 손 모양의 좌표와 각도의 패턴 파악 데이터

#테스트 데이터는 파악한 패턴이 올바른지 검증할 데이터

X_train, X_test, y_train, y_test = train_test_split(X_data, y_data, test_size=0.1)

In [26]:
#학습데이터 (손좌표와 각도)
X_train

array([[[ 5.18493950e-01,  6.22846067e-01,  4.04014230e-07, ...,
          8.74940968e+00,  1.07848668e+00,  1.33122015e+00],
        [ 5.21493018e-01,  6.24146461e-01,  3.94525898e-07, ...,
          8.61462975e+00,  1.28775620e+00,  1.68502772e+00],
        [ 5.25886714e-01,  6.22609794e-01,  3.87473875e-07, ...,
          8.83050251e+00,  9.99592721e-01,  1.30319643e+00],
        [ 5.41218698e-01,  6.21566296e-01,  3.51160196e-07, ...,
          8.15503788e+00,  1.86735380e+00,  2.99208975e+00],
        [ 5.46963871e-01,  6.22209489e-01,  3.45892403e-07, ...,
          8.42227936e+00,  2.94228363e+00,  1.63594401e+00]],

       [[ 5.37535310e-01,  5.14124274e-01,  3.55102742e-07, ...,
          3.26215196e+00,  4.35340500e+00,  1.81121528e+00],
        [ 5.35843551e-01,  5.11068046e-01,  3.56060667e-07, ...,
          3.82854939e+00,  3.80220532e+00,  1.44242787e+00],
        [ 5.34100652e-01,  5.10193050e-01,  3.33596063e-07, ...,
          5.04412699e+00,  5.47450686e+00,  1.29120

In [27]:
#학습데이터 (수어 단어)
y_train[0:5]

array([[0., 1., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 1., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 1., 0., 0., 0., 0.],
       [0., 0., 1., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 1., 0., 0., 0., 0., 0.]], dtype=float32)

In [28]:
#입력값을 읽어서 예측을 할 Sequential 객체 생성
model = Sequential()

In [29]:
#LSTM연산 실행
#input_shape(5,78) 한번에 학습하는 데이터는 5행 78열
model.add(LSTM(256, input_shape=(5,78)))

In [30]:
#A,b,c,d, .... 중 어디에 속하는 이미지 인지 예측할 준비
model.add(Flatten())

In [31]:
#model.add(Dense(128)): 각 액션의 손위치와 각도 데이터에서 128가지 공통점을 찾음
model.add(Dense(128, activation='relu'))

In [32]:
#model.add(Dropout(0.5) ) : 128가지 공통점이 없는 경우 랜덤하게 50%만 공통점 찾음
model.add(Dropout(0.5) )

In [33]:
#model.add(Dense(64)): 각 액션의 손위치와 각도 데이터에서 64가지 공통점을 찾음
model.add(Dense(64, activation='relu'))

In [34]:
#model.add(Dropout(0.5) ) : 64가지 공통점이 없는 경우 랜덤하게 50%만 공통점 찾음
model.add(Dropout(0.5) )

In [35]:
#model.add(Dense(32)): 각 액션의 손위치와 각도 데이터에서 32가지 공통점을 찾음
model.add(Dense(32, activation='relu'))

In [36]:
#model.add(Dropout(0.5) ) : 32가지 공통점이 없는 경우 랜덤하게 50%만 공통점 찾음
model.add(Dropout(0.5) )

In [37]:
#model.add(Dense( Len(gesture)-> 10, activation="softmax")): A,B,C .. J 10 (=Len(gesture)) 가지 중
# 어디에 속하는 손 좌표와 각도 인지 예측
model.add(Dense(len(gesture), activation='softmax'))

In [38]:
#optimizer='adam' : AdamOptimizer를 이용해서 패턴을 찾음

#categorical_crossentropy : 3개 이상으로 분류 (A,B,C .. J 10가지 이므로 3개이상 분류)

#metrics=['acc'] : 학습한 데이터가 얼마나 정확한지 정확도를 출력

model.compile(optimizer='adam', loss='categorical_crossentropy', metrics=['acc'])

In [39]:
# 학습한 결과 저장하도록 설정
cb_checkpoint = ModelCheckpoint(filepath="c://ai_project01/hand_lstm_train_result/", # 학습한 결과 저장할 폴더 설정
                                monitor='val_acc', # 저장할 조건 val_acc (테스트 데이터의 정확도) 가 가장 높은 결과 저장
                                save_best_only=True # 가장 정확도가 높은 모델 1개만 저장
                                )

In [40]:
# 학습은 100 번 반복해서 A, B,C .. J 손 좌표와 각도의 특징을 파악하게 진행 할것임
# 100 번 반복 전에 더이상 정확도가 높아지지 않으면 중간에 반복 종료
earlystopping = EarlyStopping(monitor='val_loss',
                              patience=30,         #30회 반복할 동안 정확도가 높아지지 않으면 반복 종료
                             )

In [42]:
#학습 시작
model.fit(
        X_train, #손동작 좌표와 각도 데이터
        y_train, #어떤 손동작인지 데이터 A -> 1000000000 B->0100000000 C->0010000000 .. J ->0000000001
        validation_data=(X_test, y_test), #테스트데이터 한번 학습이 끝날때 마다 검증
        epochs=100,         #100 번 반복해서 A,B,C .. J 손 좌표와 각도의 패턴을 파악
        callbacks=[cb_checkpoint, earlystopping] # 학습시 가장 정확도가 높은 LSTM객체를 저장
         )

Epoch 1/100
32/32 [==============================] - 0s 11ms/step - loss: 0.1277 - acc: 0.9573 - val_loss: 0.0566 - val_acc: 0.9732
Epoch 2/100
32/32 [==============================] - 0s 6ms/step - loss: 0.1504 - acc: 0.9514 - val_loss: 0.0529 - val_acc: 0.9732
Epoch 3/100
32/32 [==============================] - 0s 5ms/step - loss: 0.1293 - acc: 0.9504 - val_loss: 0.2213 - val_acc: 0.9375
Epoch 4/100
32/32 [==============================] - 0s 5ms/step - loss: 0.1692 - acc: 0.9385 - val_loss: 0.1867 - val_acc: 0.9286
Epoch 5/100
32/32 [==============================] - 0s 4ms/step - loss: 0.1609 - acc: 0.9385 - val_loss: 0.1100 - val_acc: 0.9554
Epoch 6/100
32/32 [==============================] - 0s 4ms/step - loss: 0.1528 - acc: 0.9504 - val_loss: 0.0901 - val_acc: 0.9464
Epoch 7/100
32/32 [==============================] - 0s 4ms/step - loss: 0.1525 - acc: 0.9544 - val_loss: 0.0770 - val_acc: 0.9732
Epoch 8/100
32/32 [==============================] - 0s 4ms/step - loss: 0.1411 - 